# model_name: causal_wan
# generator_ckpt: checkpoints/ode_init.pt
generator_fsdp_wrap_strategy: size
real_score_fsdp_wrap_strategy: size
fake_score_fsdp_wrap_strategy: size
text_encoder_fsdp_wrap_strategy: size
real_name: Wan2.1-T2V-1.3B
generator_grad:
  model: true
denoising_step_list:
- 1000
- 750
- 500
- 250
mixed_precision: true
seed: 0
wandb_host: https://api.wandb.ai
wandb_key: 8d9f4b39abd68eb4e29f6fc010b7ee71a2207cde
wandb_entity: wlsaidhi
wandb_project: wan_ode_init
wandb_name: SF_wan_causal_ode_1.3B_new
sharding_strategy: hybrid_full
lr: 2.0e-06
# lr: 1e-5
beta1: 0.9
beta2: 0.999
data_path: /mnt/weka/home/hao.zhang/wl/sf2/preprocessed_lmdb_ode_450/
batch_size: 1
log_iters: 1000
output_path: manual_ode_init
distribution_loss: ode
trainer: ode
gradient_checkpointing: true
num_frame_per_block: 3
warp_denoising_step: true
model_kwargs:
  timestep_shift: 5.0