model_name: causal_wan
generator_ckpt: /mnt/weka/home/hao.zhang/official_ode_init_wan22_high_4steps/checkpoint_model_002000/model.pt
generator_grad:
  model: true
denoising_step_list:
- 1000
- 550
- 0
denoising_step_index:
- 0
- 3
- 4
warp_denoising_step: true
generator_fsdp_wrap_strategy: size
text_encoder_fsdp_wrap_strategy: size
mixed_precision: true
seed: 0
wandb_host: https://api.wandb.ai
wandb_key: 50632ebd88ffd970521cec9ab4a1a2d7e85bfc45
wandb_entity: zhouw-jerry2017-georgia-institute-of-technology
wandb_project: wan_ode_init
wandb_name: SF_wan2.2_high_noise_ode_init_x0
sharding_strategy: hybrid_full
lr: 2.0e-06
beta1: 0.9
beta2: 0.999
data_path: /mnt/sharefs/users/hao.zhang/klin/preproc/data/sf-lmdb-a14-16k-trunc_high/
batch_size: 2
log_iters: 400
distribution_loss: ode
trainer: ode
gradient_checkpointing: true
num_frame_per_block: 3
model_kwargs:
  timestep_shift: 12.0
  model_dir: /mnt/sharefs/users/hao.zhang/wl/models/Wan2.2-T2V-A14B/high_noise_model/